### ISSUE TITLE
The console log is exposed the password as a string and token

### ISSUE THREAD

**Issue by HelloYeew** [patkamon/skdue#104]
https://user-images.githubusercontent.com/68165621/142825263-2c9cf173-f489-49b2-b739-f7860329afc5.mp4

As you see, my password is logged as a string in console and other of my information like token is exposed in console too.

# Step to reproduce
1. Open console
2. Just login normally
3. In console, it's show all transaction and the my password too.

**Comment by Ditthapeem** [comment]
Thanks for your report, this bug is fixed. Please check it out on our latest deployed application.
