### ISSUE TITLE
Website return fail with code 400 when you create new activity that have same name with other activity. 

### ISSUE THREAD

**Issue by SainTurDaY27** [patkamon/skdue#105]
I have test for creating activity name "test". At the first time it doesn't have any error. But when I create the new activity name "test" which time is not config with the first one. It's return this statement.
![image](https://user-images.githubusercontent.com/74703120/142826270-65338022-afcd-4cc9-9b30-c36cdf42e906.png)

**Comment by natchanon-space** [comment]
You are trying to create an event with the name that already exist in your calendar, so it make sense that the web server return 400 (Bad Request) for you.

**Comment by pontakornth** [comment]
> You are trying to create an event with the name that already exist in your calendar, so it make sense that the web server return 400 (Bad Request) for you.

That's understandable. I think having more descriptive error message is better. Users may forget the event name they created.

**Comment by SainTurDaY27** [comment]
@natchanon-space For example, If you have activity name "Project meeting" that you have to go every week, or let say you have a weekly event. How do you do when you want to create this activity for next week? Like "Project meeting week1", "Project meeting week2" ?

**Comment by Ditthapeem** [comment]
Thank you for your recommend, this feature is included on our latest deployed application. Please check it out on our application.
