### ISSUE TITLE
[BUG]: Profile Setting | Empty upload profile image form cause image not found.

### ISSUE THREAD

**Issue by vitvara** [patkamon/skdue#120]
## Step to reproduce
- Login
- Goto setting
- Click button Done.

## Bug screen shot
<img width="445" alt="image" src="https://user-images.githubusercontent.com/69972884/143685277-dbbef5d9-89e0-4778-b870-9a61733e6907.png">

**Comment by Ditthapeem** [comment]
Thanks for your report, this bug is fixed. Please check it out on our latest deployed application.
