### ISSUE TITLE
[BUG] Profile setting - text file can upload as profile picture

### ISSUE THREAD

**Issue by nabhan-au** [patkamon/skdue#121]
## Description
I can upload text file to profile image

## Step To Reproduce the bug:
1. Go to home page and login
2. Go to profile setting
3. Click upload profile with .txt file
4. Click done

## Screenshot
![Screenshot 2021-11-27 212212](https://user-images.githubusercontent.com/70481664/143685553-d9f3d438-1208-488a-a7d2-b60b7ed8814d.jpg)

**Comment by touchtool** [comment]
Thanks for your report, this bug is fixed. Please check it out on our latest deployed application.
