### ISSUE TITLE
Got Request Failed 400 after editing profile.

### ISSUE THREAD

**Issue by tboonma** [patkamon/skdue#122]
## Step to reproduce
- Login and go to profile page.
- Try edit something and click Done.

## Reference
<img width="1542" alt="Screen Shot 2564-11-27 at 21 22 43" src="https://user-images.githubusercontent.com/63687258/143685583-8599e4f5-824f-4b7a-a209-13074a875897.png">

**Comment by Ditthapeem** [comment]
Thanks for your report, this bug is fixed. Please check it out on our latest deployed application.
